# FinBERT Modular Profiling Notebook

This notebook provides a modular framework for profiling the baseline FinBERT model.

**Device Support:**
- **CUDA (NVIDIA GPUs)**: Full profiling with CPU and CUDA time tracking
- **MPS (Apple Silicon)**: CPU time profiling only (GPU execution not separately tracked)
- **CPU**: Standard CPU profiling

## Quick Start Guide

### How to Use This Modular Notebook

1. **Run Setup Cells (1-8)**: Execute all cells from the beginning through "Setup Paths" to load utilities and configuration.

2. **Configure Your Experiment (Cell 7)**: 
   - Set `SELECTED_VARIANT` to `'baseline'` or `'quantized_int8'`
   - Set `TRAIN_NEW_MODEL = True` if you want to train from scratch, or `False` to use existing model
   - Adjust `USE_GPU` and other settings as needed

3. **Optional: Train Model (Cell 9)**:
   - Only runs if `TRAIN_NEW_MODEL = True`
   - Trains with profiling on first epoch, then continues full training

4. **Load Model Variant (Cell 10)**:
   - Automatically loads the selected model variant (baseline or quantized)

5. **Profile Inference (Cell 11)**:
   - Runs profiled inference on the test text
   - Displays performance metrics and predictions

### Available Model Variants

- **baseline**: Standard FinBERT model (FP32, ~438MB)
- **quantized_int8**: INT8 post-training quantized model (3-4x smaller, GPU-accelerated)
  - Requires: GPU with CUDA support
  - Benefits: Reduced memory footprint, faster inference
  - Trade-off: Slight accuracy reduction (~1-3%)

### Example Workflow

```python
# 1. Change configuration
SELECTED_VARIANT = 'quantized_int8'  # or 'baseline'
TRAIN_NEW_MODEL = False

# 2. Run cells 8-11 to profile the model
```

## 1. Setup: Imports and Constants

In [1]:
# Core imports
from pathlib import Path
import shutil
import os
import logging
import sys
import time
from collections import defaultdict
sys.path.append('..')

# NLP & ML
from textblob import TextBlob
from pprint import pprint
from sklearn.metrics import classification_report
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import nltk

# FinBERT
from finbert.finbert import *
import finbert.utils as tools

# PyTorch
import torch
import torch.nn as nn
from torch.profiler import profile, record_function, ProfilerActivity
import torch.ao.quantization

# Data processing
import numpy as np
import pandas as pd

# Notebook utilities
%load_ext autoreload
%autoreload 2

# Global configuration
project_dir = Path.cwd().parent
pd.set_option('max_colwidth', None)

# Constants
LABEL_LIST = ['positive', 'negative', 'neutral']
LABEL_DICT = {0: 'positive', 1: 'negative', 2: 'neutral'}
BASE_TOKENIZER = 'bert-base-uncased'

print("✓ Imports loaded successfully")
print(f"✓ Project directory: {project_dir}")
print(f"✓ PyTorch version: {torch.__version__}")
print(f"✓ CUDA available: {torch.cuda.is_available()}")

✓ Imports loaded successfully
✓ Project directory: /home/tfs2123/finBERT
✓ PyTorch version: 2.9.1+cu128
✓ CUDA available: True

In [2]:
logging.basicConfig(format = '%(asctime)s - %(levelname)s - %(name)s -   %(message)s',
                    datefmt = '%m/%d/%Y %H:%M:%S',
                    level = logging.ERROR)

## 2. Helper Utilities

In [3]:
def get_model_size_mb(model):
    """Calculate model size in MB"""
    param_size = 0
    for param in model.parameters():
        param_size += param.nelement() * param.element_size()
    buffer_size = 0
    for buffer in model.buffers():
        buffer_size += buffer.nelement() * buffer.element_size()
    
    size_mb = (param_size + buffer_size) / 1024**2
    return size_mb


def get_profiler_activities(device):
    """Get appropriate profiler activities based on device"""
    activities = [ProfilerActivity.CPU]
    if device.type == "cuda":
        activities.append(ProfilerActivity.CUDA)
    return activities


def print_profiler_results(prof, device, title="Profiling Results"):
    """Pretty print profiler results"""
    print(f"\n{'='*80}")
    print(f"{title}")
    print(f"{'='*80}\n")
    
    print("By CPU Time:")
    print(prof.key_averages().table(sort_by="cpu_time_total", row_limit=20))
    
    if device.type == "cuda":
        print("\nBy CUDA Time:")
        print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=20))
    
    print(f"\n{'='*80}\n")


def setup_nltk_data():
    """Download necessary NLTK data"""
    try:
        nltk.download('punkt', quiet=True)
        nltk.download('punkt_tab', quiet=True)
    except:
        pass


def print_device_info(device):
    """Print device information"""
    print(f"\n{'='*80}")
    print(f"Device: {device}")
    if device.type == "cuda":
        print(f"GPU Name: {torch.cuda.get_device_name(device)}")
        print(f"GPU Memory: {torch.cuda.get_device_properties(device).total_memory / 1024**3:.1f} GB")
    elif device.type == "mps":
        print("Note: MPS profiling shows CPU time only. Actual GPU execution time not separately tracked.")
    print(f"{'='*80}\n")


def quantize_int8_model(model, calibration_loader=None, device='cuda'):
    """
    Apply INT8 post-training quantization using TorchAO for GPU inference.
    
    Args:
        model: The model to quantize
        calibration_loader: Optional data loader for calibration (not used for dynamic quantization)
        device: Device to run quantization on
    
    Returns:
        Quantized model ready for GPU inference
    """
    try:
        from torchao.quantization import quantize_, int8_dynamic_activation_int4_weight
        
        # Move model to GPU for quantization
        model = model.to(device)
        model.eval()
        
        # Apply dynamic INT8 activation with INT4 weight quantization
        # This provides good compression with minimal accuracy loss
        quantize_(model, int8_dynamic_activation_int4_weight())
        
        print("✓ Applied TorchAO INT8 dynamic quantization")
        return model
        
    except ImportError:
        print("⚠ TorchAO not available, falling back to torch.ao.quantization")
        # Fallback to standard PyTorch dynamic quantization (CPU-optimized)
        quantized_model = torch.ao.quantization.quantize_dynamic(
            model.cpu(),
            {torch.nn.Linear},
            dtype=torch.qint8
        )
        print("✓ Applied torch.ao dynamic quantization (CPU-optimized)")
        return quantized_model.to(device)


print("✓ Helper utilities loaded")

✓ Helper utilities loaded

## 3. Data and Training Utilities

In [4]:
def setup_paths(project_dir):
    """Setup and return paths for model and data"""
    cl_path = project_dir / 'models' / 'sentiment'
    cl_data_path = project_dir / 'data' / 'sentiment_data'
    return cl_path, cl_data_path


def create_finbert_config(cl_path, cl_data_path, bert_model, **kwargs):
    """Create FinBERT configuration with defaults"""
    defaults = {
        'data_dir': cl_data_path,
        'bert_model': bert_model,
        'num_train_epochs': 6,
        'model_dir': cl_path,
        'max_seq_length': 48,
        'train_batch_size': 32,
        'learning_rate': 2e-5,
        'output_mode': 'classification',
        'warm_up_proportion': 0.2,
        'local_rank': -1,
        'discriminate': True,
        'gradual_unfreeze': True
    }
    defaults.update(kwargs)
    return Config(**defaults)


def initialize_finbert(config, base_model='bert-base-uncased', use_profiling=True):
    """Initialize FinBERT instance with configuration"""
    if use_profiling:
        finbert = ProfiledFinBert(config)
    else:
        finbert = FinBert(config)
    
    finbert.base_model = base_model
    finbert.config.discriminate = True
    finbert.config.gradual_unfreeze = True
    finbert.prepare_model(label_list=LABEL_LIST)
    
    return finbert


def train_model(finbert, train_data, model):
    """Train the model and return the trained model"""
    trained_model = finbert.train(train_examples=train_data, model=model)
    return trained_model


def evaluate_model(finbert, test_data, model):
    """Evaluate model on test data"""
    results = finbert.evaluate(examples=test_data, model=model)
    results['prediction'] = results.predictions.apply(lambda x: np.argmax(x, axis=0))
    return results


def generate_classification_report(results, finbert, cols=['labels', 'prediction', 'predictions']):
    """Generate and print classification report"""
    from torch.nn import CrossEntropyLoss
    
    cs = CrossEntropyLoss(weight=finbert.class_weights)
    loss = cs(torch.tensor(list(results[cols[2]])), torch.tensor(list(results[cols[0]])))
    
    accuracy = (results[cols[0]] == results[cols[1]]).sum() / results.shape[0]
    
    print(f"Loss: {loss:.2f}")
    print(f"Accuracy: {accuracy:.2f}")
    print("\nClassification Report:")
    print(classification_report(results[cols[0]], results[cols[1]]))
    
    return {'loss': loss.item(), 'accuracy': accuracy}


print("✓ Data and training utilities loaded")

✓ Data and training utilities loaded

## 4. Model Variant Registry

This section defines model variants for profiling, including baseline and quantized models.

### Post-Training Quantization (PTQ)

The notebook supports INT8 post-training quantization via TorchAO for GPU-accelerated inference:

- **Method**: `int8_dynamic_activation_int4_weight` (TorchAO)
- **Fallback**: `torch.ao.quantization.quantize_dynamic` if TorchAO unavailable
- **Benefits**: 3-4x memory reduction, faster inference on GPU
- **Trade-offs**: ~1-3% accuracy reduction (typical for BERT models)

In [18]:
class ModelVariant:
    """Base class for model variants"""
    def __init__(self, name, description):
        self.name = name
        self.description = description
        self.model = None
        self.size_mb = None
    
    def load_model(self, model_path):
        """Load model - to be implemented by subclasses"""
        raise NotImplementedError
    
    def get_info(self):
        """Get variant information"""
        return {
            'name': self.name,
            'description': self.description,
            'size_mb': self.size_mb
        }


class BaselineVariant(ModelVariant):
    """Standard FinBERT model without any optimization"""
    def __init__(self):
        super().__init__(
            name="baseline",
            description="Standard FinBERT model (FP32)"
        )
    
    def load_model(self, model_path):
        """Load baseline model"""
        self.model = AutoModelForSequenceClassification.from_pretrained(
            model_path, cache_dir=None, num_labels=3
        )
        self.size_mb = get_model_size_mb(self.model)
        return self.model


from transformers import AutoModelForSequenceClassification, BitsAndBytesConfig

class QuantizedInt8Variant(ModelVariant):
    """INT8 quantized FinBERT using BitsAndBytes 8-bit loading (fastest path)"""
    def __init__(self):
        super().__init__(
            name="quantized_int8",
            description="INT8 8-bit quantization via BitsAndBytes (3-4x compression)"
        )
    
    def load_model(self, model_path):
        """Load model directly in 8-bit using BitsAndBytes"""

        # Configure bnb for 8-bit quantization
        bnb_config = BitsAndBytesConfig(
            load_in_8bit=True,
            llm_int8_threshold=6.0,     # defaults are fine
            llm_int8_has_fp16_weight=False
        )

        # Load model in 8-bit
        self.model = AutoModelForSequenceClassification.from_pretrained(
            model_path,
            num_labels=3,
            quantization_config=bnb_config,
            device_map="auto"
        )

        # Compute storage size (weights only)
        self.size_mb = get_model_size_mb(self.model)
        
        return self.model



# Registry of available variants
MODEL_VARIANTS = {
    'baseline': BaselineVariant(),
    'quantized_int8': QuantizedInt8Variant()
}


def list_available_variants():
    """List all available model variants"""
    print("Available Model Variants:")
    print("=" * 80)
    for name, variant in MODEL_VARIANTS.items():
        print(f"\n{name}:")
        print(f"  Description: {variant.description}")
    print("\n" + "=" * 80)


def load_model_variant(variant_name, model_path):
    """Load a specific model variant"""
    if variant_name not in MODEL_VARIANTS:
        raise ValueError(f"Unknown variant: {variant_name}. Available: {list(MODEL_VARIANTS.keys())}")
    
    variant = MODEL_VARIANTS[variant_name]
    print(f"\nLoading model variant: {variant.name}")
    print(f"Description: {variant.description}")
    
    model = variant.load_model(model_path)
    
    print(f"✓ Model loaded successfully")
    print(f"✓ Model size: {variant.size_mb:.2f} MB")
    
    return model, variant


print("✓ Model variant registry loaded")
list_available_variants()

✓ Model variant registry loaded
Available Model Variants:
================================================================================

baseline:
  Description: Standard FinBERT model (FP32)

quantized_int8:
  Description: INT8 8-bit quantization via BitsAndBytes (3-4x compression)

================================================================================

## 5. Profiling API

Generic profiling functions that work with any model variant.

In [ ]:
def profile_inference(model, text, variant_name="unknown", use_gpu=False, gpu_name='cuda:0', batch_size=5):
    """
    Profile model inference performance.
    
    Args:
        model: Model to profile
        text: Text to analyze
        variant_name: Name of the model variant
        use_gpu: Whether to use GPU
        gpu_name: GPU device name
        batch_size: Batch size for inference
    
    Returns:
        results_df: DataFrame with predictions
        metrics: Dictionary with performance metrics
    """
    from nltk.tokenize import sent_tokenize
    from finbert.utils import InputExample, convert_examples_to_features, softmax, chunks, get_device
    
    # Setup NLTK
    setup_nltk_data()
    
    model.eval()
    tokenizer = AutoTokenizer.from_pretrained(BASE_TOKENIZER)
    
    # Device selection
    if use_gpu:
        device = get_device(no_cuda=False)
        if device.type == "cuda" and gpu_name.startswith("cuda:"):
            device = torch.device(gpu_name)
    else:
        device = torch.device("cpu")
    
    print_device_info(device)
    
    # Check if model is already on device (e.g., BitsAndBytes quantized models)
    is_quantized = hasattr(model, 'is_loaded_in_8bit') and model.is_loaded_in_8bit
    is_quantized = is_quantized or (hasattr(model, 'is_loaded_in_4bit') and model.is_loaded_in_4bit)
    
    # Only move model if it's not already quantized and placed
    if not is_quantized:
        model = model.to(device)
    else:
        print(f"✓ Model already quantized and placed on device (skipping .to() call)")
        # For quantized models, get the actual device from model
        if hasattr(model, 'device'):
            device = model.device
        elif hasattr(model, 'hf_device_map'):
            # BitsAndBytes models have device_map
            device = torch.device('cuda:0')  # Usually on cuda:0
    
    result = pd.DataFrame(columns=['sentence', 'logit', 'prediction', 'sentiment_score'])
    
    # Setup profiler
    activities = get_profiler_activities(device)
    
    total_inference_time = 0
    
    with profile(
        activities=activities,
        record_shapes=True,
        profile_memory=True,
        with_stack=False
    ) as prof:
        
        with record_function("sentence_tokenization"):
            sentences = sent_tokenize(text)
        
        for batch in chunks(sentences, batch_size):
            with record_function("create_examples"):
                examples = [InputExample(str(i), sentence) for i, sentence in enumerate(batch)]
            
            with record_function("convert_to_features"):
                features = convert_examples_to_features(examples, LABEL_LIST, 64, tokenizer)
            
            with record_function("prepare_tensors"):
                all_input_ids = torch.tensor([f.input_ids for f in features], dtype=torch.long).to(device)
                all_attention_mask = torch.tensor([f.attention_mask for f in features], dtype=torch.long).to(device)
                all_token_type_ids = torch.tensor([f.token_type_ids for f in features], dtype=torch.long).to(device)
            
            with torch.no_grad():
                # Remove the model_to_device profiling section for quantized models
                if not is_quantized:
                    with record_function("model_to_device"):
                        model = model.to(device)
                
                with record_function("inference_forward"):
                    start_time = time.time()
                    logits = model(input_ids=all_input_ids, attention_mask=all_attention_mask, token_type_ids=all_token_type_ids)[0]
                    total_inference_time += time.time() - start_time
                
                with record_function("postprocess_results"):
                    logits = softmax(np.array(logits.cpu()))
                    sentiment_score = pd.Series(logits[:, 0] - logits[:, 1])
                    predictions = np.squeeze(np.argmax(logits, axis=1))
                    
                    batch_result = {
                        'sentence': batch,
                        'logit': list(logits),
                        'prediction': predictions,
                        'sentiment_score': sentiment_score
                    }
                    
                    batch_result = pd.DataFrame(batch_result)
                    result = pd.concat([result, batch_result], ignore_index=True)
    
    # Print profiler results
    print_profiler_results(prof, device, title=f"Inference Profiling - {variant_name}")
    
    result['prediction'] = result.prediction.apply(lambda x: LABEL_DICT[x])
    
    metrics = {
        'variant': variant_name,
        'total_sentences': len(sentences),
        'inference_time_ms': total_inference_time * 1000,
        'time_per_sentence_ms': (total_inference_time * 1000) / len(sentences),
        'device': str(device),
        'is_quantized': is_quantized
    }
    
    print(f"\nInference Summary:")
    print(f"  Total sentences: {metrics['total_sentences']}")
    print(f"  Total inference time: {metrics['inference_time_ms']:.2f} ms")
    print(f"  Time per sentence: {metrics['time_per_sentence_ms']:.2f} ms")
    if is_quantized:
        print(f"  ✓ Quantized model profiled successfully")
    
    return result, metrics

✓ Profiling API loaded

## 6. ProfiledFinBert Class (for Training)

Extended FinBert class with profiling instrumentation for training.

In [ ]:
class ProfiledFinBert(FinBert):
    """Extended FinBert class with profiling instrumentation.
    
    Note: GPU-specific profiling (ProfilerActivity.CUDA) only works with NVIDIA CUDA devices.
    For MPS (Apple Silicon), only CPU profiling is available, though actual computation runs on GPU.
    """
    
    def __init__(self, config):
        super().__init__(config)
        self.profile_results = {}
    
    def train(self, train_examples, model):
        """
        Trains the model with profiling instrumentation.
        """
        validation_examples = self.get_data('validation')
        global_step = 0
        self.validation_losses = []
        
        # Training
        train_dataloader = self.get_loader(train_examples, 'train')
        model.train()
        step_number = len(train_dataloader)
        
        # Setup profiler - CUDA profiling only works with NVIDIA GPUs, not MPS
        activities = [ProfilerActivity.CPU]
        if self.device.type == "cuda":
            activities.append(ProfilerActivity.CUDA)
        
        print("\\n" + "="*80)
        print("Starting Profiled Training")
        print(f"Device: {self.device}")
        print(f"Profiling activities: {activities}")
        if self.device.type == "mps":
            print("Note: MPS profiling shows CPU time only. Actual GPU execution time not separately tracked.")
        print("="*80 + "\\n")
        
        i = 0
        
        with profile(
            activities=activities,
            record_shapes=True,
            profile_memory=True,
            with_stack=False
        ) as prof:
            
            for epoch in trange(int(self.config.num_train_epochs), desc="Epoch"):
                model.train()
                tr_loss = 0
                nb_tr_examples, nb_tr_steps = 0, 0
                
                for step, batch in enumerate(tqdm(train_dataloader, desc='Iteration')):
                    
                    # Gradual unfreezing logic
                    if (self.config.gradual_unfreeze and i == 0):
                        for param in model.bert.parameters():
                            param.requires_grad = False
                    
                    if (step % (step_number // 3)) == 0:
                        i += 1
                    
                    if (self.config.gradual_unfreeze and i > 1 and i < self.config.encoder_no):
                        for k in range(i - 1):
                            try:
                                for param in model.bert.encoder.layer[self.config.encoder_no - 1 - k].parameters():
                                    param.requires_grad = True
                            except:
                                pass
                    
                    if (self.config.gradual_unfreeze and i > self.config.encoder_no + 1):
                        for param in model.bert.embeddings.parameters():
                            param.requires_grad = True
                    
                    # Data loading profiling
                    with record_function("data_transfer"):
                        batch = tuple(t.to(self.device) for t in batch)
                        input_ids, attention_mask, token_type_ids, label_ids, agree_ids = batch
                    
                    # Forward pass profiling
                    with record_function("forward_pass"):
                        logits = model(input_ids, attention_mask, token_type_ids)[0]
                    
                    # Loss calculation profiling
                    with record_function("loss_calculation"):
                        weights = self.class_weights.to(self.device)
                        if self.config.output_mode == "classification":
                            loss_fct = CrossEntropyLoss(weight=weights)
                            loss = loss_fct(logits.view(-1, self.num_labels), label_ids.view(-1))
                        elif self.config.output_mode == "regression":
                            loss_fct = MSELoss()
                            loss = loss_fct(logits.view(-1), label_ids.view(-1))
                        
                        if self.config.gradient_accumulation_steps > 1:
                            loss = loss / self.config.gradient_accumulation_steps
                    
                    # Backward pass profiling
                    with record_function("backward_pass"):
                        loss.backward()
                    
                    tr_loss += loss.item()
                    nb_tr_examples += input_ids.size(0)
                    nb_tr_steps += 1
                    
                    # Optimizer step profiling
                    if (step + 1) % self.config.gradient_accumulation_steps == 0:
                        with record_function("optimizer_step"):
                            if self.config.fp16:
                                lr_this_step = self.config.learning_rate * warmup_linear(
                                    global_step / self.num_train_optimization_steps, self.config.warm_up_proportion)
                                for param_group in self.optimizer.param_groups:
                                    param_group['lr'] = lr_this_step
                            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                            self.optimizer.step()
                            self.scheduler.step()
                            self.optimizer.zero_grad()
                            global_step += 1
                    
                    # Only profile first epoch to save time
                    if epoch == 0 and step >= 20:
                        break
                
                # Break after first epoch for profiling
                if epoch == 0:
                    print("\\n" + "="*80)
                    print("Profiling complete for first epoch (20 steps)")
                    print("Continuing full training without profiling...")
                    print("="*80 + "\\n")
                    break
        
        # Print profiler results
        print("\\n" + "="*80)
        print("PROFILING RESULTS - Training")
        print("="*80 + "\\n")
        
        print("\\nBy CPU Time:")
        print(prof.key_averages().table(sort_by="cpu_time_total", row_limit=20))
        
        if self.device.type == "cuda":
            print("\\nBy CUDA Time:")
            print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=20))
        
        print("\\n" + "="*80 + "\\n")
        
        # Store results
        self.profile_results['training'] = prof.key_averages()
        
        # Continue with full training without profiling
        for epoch in trange(int(self.config.num_train_epochs), desc="Epoch"):
            model.train()
            tr_loss = 0
            nb_tr_examples, nb_tr_steps = 0, 0
            
            for step, batch in enumerate(tqdm(train_dataloader, desc='Iteration')):
                
                if (self.config.gradual_unfreeze and i == 0):
                    for param in model.bert.parameters():
                        param.requires_grad = False
                
                if (step % (step_number // 3)) == 0:
                    i += 1
                
                if (self.config.gradual_unfreeze and i > 1 and i < self.config.encoder_no):
                    for k in range(i - 1):
                        try:
                            for param in model.bert.encoder.layer[self.config.encoder_no - 1 - k].parameters():
                                param.requires_grad = True
                        except:
                            pass
                
                if (self.config.gradual_unfreeze and i > self.config.encoder_no + 1):
                    for param in model.bert.embeddings.parameters():
                        param.requires_grad = True
                
                batch = tuple(t.to(self.device) for t in batch)
                input_ids, attention_mask, token_type_ids, label_ids, agree_ids = batch
                
                logits = model(input_ids, attention_mask, token_type_ids)[0]
                weights = self.class_weights.to(self.device)
                
                if self.config.output_mode == "classification":
                    loss_fct = CrossEntropyLoss(weight=weights)
                    loss = loss_fct(logits.view(-1, self.num_labels), label_ids.view(-1))
                elif self.config.output_mode == "regression":
                    loss_fct = MSELoss()
                    loss = loss_fct(logits.view(-1), label_ids.view(-1))
                
                if self.config.gradient_accumulation_steps > 1:
                    loss = loss / self.config.gradient_accumulation_steps
                else:
                    loss.backward()
                
                tr_loss += loss.item()
                nb_tr_examples += input_ids.size(0)
                nb_tr_steps += 1
                
                if (step + 1) % self.config.gradient_accumulation_steps == 0:
                    if self.config.fp16:
                        lr_this_step = self.config.learning_rate * warmup_linear(
                            global_step / self.num_train_optimization_steps, self.config.warm_up_proportion)
                        for param_group in self.optimizer.param_groups:
                            param_group['lr'] = lr_this_step
                    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                    self.optimizer.step()
                    self.scheduler.step()
                    self.optimizer.zero_grad()
                    global_step += 1
            
            # Validation
            validation_loader = self.get_loader(validation_examples, phase='eval')
            model.eval()
            
            valid_loss, valid_accuracy = 0, 0
            nb_valid_steps, nb_valid_examples = 0, 0
            
            for input_ids, attention_mask, token_type_ids, label_ids, agree_ids in tqdm(validation_loader, desc="Validating"):
                input_ids = input_ids.to(self.device)
                attention_mask = attention_mask.to(self.device)
                token_type_ids = token_type_ids.to(self.device)
                label_ids = label_ids.to(self.device)
                agree_ids = agree_ids.to(self.device)
                
                with torch.no_grad():
                    logits = model(input_ids, attention_mask, token_type_ids)[0]
                    
                    if self.config.output_mode == "classification":
                        loss_fct = CrossEntropyLoss(weight=weights)
                        tmp_valid_loss = loss_fct(logits.view(-1, self.num_labels), label_ids.view(-1))
                    elif self.config.output_mode == "regression":
                        loss_fct = MSELoss()
                        tmp_valid_loss = loss_fct(logits.view(-1), label_ids.view(-1))
                    
                    valid_loss += tmp_valid_loss.mean().item()
                    nb_valid_steps += 1
            
            valid_loss = valid_loss / nb_valid_steps
            self.validation_losses.append(valid_loss)
            print("Validation losses: {}".format(self.validation_losses))
            
            if valid_loss == min(self.validation_losses):
                try:
                    os.remove(self.config.model_dir / ('temporary' + str(best_model)))
                except:
                    print('No best model found')
                torch.save({'epoch': str(epoch), 'state_dict': model.state_dict()},
                           self.config.model_dir / ('temporary' + str(epoch)))
                best_model = epoch
        
        # Save the trained model
        checkpoint = torch.load(self.config.model_dir / ('temporary' + str(best_model)))
        model.load_state_dict(checkpoint['state_dict'])
        model_to_save = model.module if hasattr(model, 'module') else model
        output_model_file = os.path.join(self.config.model_dir, WEIGHTS_NAME)
        torch.save(model_to_save.state_dict(), output_model_file)
        output_config_file = os.path.join(self.config.model_dir, CONFIG_NAME)
        with open(output_config_file, 'w') as f:
            f.write(model_to_save.config.to_json_string())
        os.remove(self.config.model_dir / ('temporary' + str(best_model)))
        
        return model

print("Profiling loaded")

---

# WORKFLOW SECTION

Below are the workflow cells that demonstrate how to use the modular system.

---

## 7. Configuration: Select Model Variant and Settings

In [20]:
# =============================================================================
# CONFIGURATION CELL - Modify these settings to change workflow behavior
# =============================================================================

# Choose which model variant to use
# Options: 'baseline', 'quantized_int8'
SELECTED_VARIANT = 'quantized_int8'

# Whether to train a new model (True) or load existing model (False)
TRAIN_NEW_MODEL = True  # Set to False if you already have a trained model

# Number of training epochs (if training)
NUM_EPOCHS = 4

# GPU settings
USE_GPU = True
GPU_NAME = 'cuda:0'

# Test text for inference profiling
TEST_TEXT = """Later that day Apple said it was revising down its earnings expectations in \
the fourth quarter of 2018, largely because of lower sales and signs of economic weakness in China. \
The news rapidly infected financial markets. Apple's share price fell by around 7% in after-hours \
trading and the decline was extended to more than 10% when the market opened. The dollar fell \
by 3.7% against the yen in a matter of minutes after the announcement, before rapidly recovering \
some ground. Asian stockmarkets closed down on January 3rd and European ones opened lower. \
Yields on government bonds fell as investors fled to the traditional haven in a market storm."""

print(f"✓ Configuration loaded")
print(f"  Selected variant: {SELECTED_VARIANT}")
print(f"  Training mode: {'Train new model' if TRAIN_NEW_MODEL else 'Load existing model'}")
print(f"  GPU enabled: {USE_GPU}")

✓ Configuration loaded
  Selected variant: quantized_int8
  Training mode: Train new model
  GPU enabled: True

## 8. Setup Paths

In [9]:
# Setup paths using the utility function
cl_path, cl_data_path = setup_paths(project_dir)

print(f"✓ Paths configured:")
print(f"  Model path: {cl_path}")
print(f"  Data path: {cl_data_path}")

✓ Paths configured:
  Model path: /home/tfs2123/finBERT/models/sentiment
  Data path: /home/tfs2123/finBERT/data/sentiment_data

## 9. Training Workflow (Optional - Only if TRAIN_NEW_MODEL = True)

Skip this section if you already have a trained model.

In [21]:
if TRAIN_NEW_MODEL:
    print("="*80)
    print("TRAINING NEW MODEL")
    print("="*80)
    
    # Clean the model path
    try:
        shutil.rmtree(cl_path)
        print("✓ Cleaned previous model directory")
    except:
        print("✓ No previous model directory to clean")
    
    # Create base BERT model
    bertmodel = AutoModelForSequenceClassification.from_pretrained(
        'bert-base-uncased', cache_dir=None, num_labels=3
    )
    
    # Create configuration
    config = create_finbert_config(
        cl_path, cl_data_path, bertmodel, 
        num_train_epochs=NUM_EPOCHS
    )
    
    # Initialize FinBERT
    finbert = initialize_finbert(config, use_profiling=True)
    
    # Get training data
    print("\n✓ Loading training data...")
    train_data = finbert.get_data('train')
    
    # Create model
    print("✓ Creating model...")
    model = finbert.create_the_model()
    
    # Train with profiling
    print("\n✓ Starting training with profiling...")
    trained_model = train_model(finbert, train_data, model)
    
    print("\n" + "="*80)
    print("TRAINING COMPLETE")
    print("="*80)
else:
    print("Skipping training - will load existing model")

================================================================================
TRAINING NEW MODEL
================================================================================
✓ Cleaned previous model directory

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
11/23/2025 07:22:44 - INFO - finbert.finbert -   device: cuda n_gpu: 1, distributed training: False, 16-bits training: False
11/23/2025 07:22:45 - INFO - finbert.utils -   *** Example ***
11/23/2025 07:22:45 - INFO - finbert.utils -   guid: train-1
11/23/2025 07:22:45 - INFO - finbert.utils -   tokens: [CLS] after the reporting period , bio ##tie north american licensing partner so ##max ##on pharmaceuticals announced positive results with na ##lm ##efe ##ne in a pilot phase 2 clinical trial for smoking ce ##ssa ##tion [SEP]
11/23/2025 07:22:45 - INFO - finbert.utils -   input_ids: 101 2044 1996 7316 2558 1010 16012 9515 2167 2137 13202 4256 2061 17848 2239 24797 2623 3893 3463 2007 6583 13728 27235 2638 1999 1037 4405 4403 1016 6612 3979 2005 9422 8292 11488 3508 102 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:22:45 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:22:45 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:22:45 - INFO - finbert.utils -   label: positive (id = 0)

✓ Loading training data...
✓ Creating model...

✓ Starting training with profiling...

11/23/2025 07:22:46 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 07:22:46 - INFO - finbert.finbert -     Num examples = 3488
11/23/2025 07:22:46 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 07:22:46 - INFO - finbert.finbert -     Num steps = 48

\n================================================================================
Starting Profiled Training
Device: cuda
Profiling activities: [<ProfilerActivity.CPU: 0>, <ProfilerActivity.CUDA: 2>]
================================================================================\n

Iteration:  18%|█▊        | 20/109 [00:01<00:08, 10.70it/s]
Epoch:   0%|          | 0/4 [00:01<?, ?it/s]

\n================================================================================
Profiling complete for first epoch (20 steps)
Continuing full training without profiling...
================================================================================\n
\n================================================================================
PROFILING RESULTS - Training
================================================================================\n
\nBy CPU Time:
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                               aten::to         0.04%     769.694us        75.54%        1.400s       4.142ms       0.000us         0.00%     502.326us       1.486us           0 B           0 B       8.15 MB           0 B           338
                                       loss_calculation         0.23%       4.285ms        75.51%        1.399s      66.636ms       0.000us         0.00%     165.439us       7.878us           0 B           0 B      22.00 KB     -20.00 KB            21
                                         aten::_to_copy         0.07%       1.238ms        75.50%        1.399s       8.328ms       0.000us         0.00%     502.326us       2.990us           0 B           0 B       8.15 MB           0 B           168
                                            aten::copy_         0.09%       1.607ms        75.39%        1.397s       7.392ms     575.956us         0.03%     575.956us       3.047us           0 B           0 B           0 B           0 B           189
                                  cudaStreamSynchronize        75.13%        1.392s        75.13%        1.392s       8.288ms       0.000us         0.00%       0.000us       0.000us           0 B           0 B           0 B           0 B           168
                                           forward_pass         5.77%     106.850ms        17.94%     332.505ms      15.834ms       0.000us         0.00%        1.671s      79.556ms           0 B         -84 B       1.97 MB     -22.64 GB            21
                                           aten::linear         0.76%      14.137ms         5.88%     108.963ms      70.118us       0.000us         0.00%        1.475s     949.389us           0 B           0 B       9.97 GB           0 B          1554
                                            aten::addmm         2.85%      52.741ms         3.89%      72.163ms      46.437us        1.475s        88.14%        1.475s     949.389us           0 B           0 B       9.97 GB       9.97 GB          1554
                                         optimizer_step         1.09%      20.122ms         2.74%      50.815ms       2.420ms       0.000us         0.00%       2.268ms     108.008us           8 B           0 B    -180.50 KB     -84.00 KB            21
                                       cudaLaunchKernel         2.17%      40.285ms         2.17%      40.285ms       8.712us       0.000us         0.00%       0.000us       0.000us           0 B           0 B           0 B           0 B          4624
enumerate(DataLoader)#_SingleProcessDataLoaderIter._...         0.85%      15.723ms         2.02%      37.400ms       1.781ms       0.000us         0.00%       0.000us       0.000us     766.50 KB     -27.26 KB           0 B           0 B            21
                                          aten::dropout         0.15%       2.817ms         1.49%      27.635ms      50.613us       0.000us         0.00%      25.208ms      46.168us           0 B           0 B       2.31 GB      -1.03 GB           546
                                       aten::layer_norm         0.16%       2.876ms         1.44%      26.740ms      50.933us       0.000us         0.00%      28.006ms      53.344us           0 B           0 B       2.31 GB      -5.80 MB           525
                                   aten::native_dropout         0.50%       9.241ms         1.34%      24.818ms      45.454us      25.208ms         1.51%      25.208ms      46.168us           0 B           0 B       3.33 GB           0 B           546
                     aten::scaled_dot_product_attention         0.18%       3.401ms         1.32%      24.467ms      97.091us       0.000us         0.00%      68.887ms     273.359us           0 B      -3.94 KB       1.11 GB           0 B           252
                                aten::native_layer_norm         0.56%      10.315ms         1.29%      23.864ms      45.455us      28.006ms         1.67%      28.006ms      53.344us           0 B           0 B       2.31 GB           0 B           525
                              Optimizer.step#AdamW.step         0.81%      14.972ms         1.23%      22.725ms       1.082ms       0.000us         0.00%       1.493ms      71.077us           8 B        -168 B      19.00 KB    -199.50 KB            21
          aten::_scaled_dot_product_efficient_attention         0.15%       2.864ms         1.05%      19.441ms      77.148us       0.000us         0.00%      68.887ms     273.359us       3.94 KB           0 B       1.11 GB           0 B           252
                                          backward_pass         0.88%      16.262ms         0.93%      17.288ms     823.233us       0.000us         0.00%      46.305us       2.205us           0 B           0 B      -1.79 MB      -1.80 MB            21
                                        aten::transpose         0.61%      11.262ms         0.87%      16.128ms       4.439us       0.000us         0.00%       0.000us       0.000us           0 B           0 B           0 B           0 B          3633
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.853s
Self CUDA time total: 1.674s

\nBy CUDA Time:
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                           forward_pass         0.00%       0.000us         0.00%       0.000us       0.000us        1.690s       100.96%        1.690s      80.475ms           0 B           0 B           0 B           0 B            21
                                           forward_pass         5.77%     106.850ms        17.94%     332.505ms      15.834ms       0.000us         0.00%        1.671s      79.556ms           0 B         -84 B       1.97 MB     -22.64 GB            21
                                           aten::linear         0.76%      14.137ms         5.88%     108.963ms      70.118us       0.000us         0.00%        1.475s     949.389us           0 B           0 B       9.97 GB           0 B          1554
                                            aten::addmm         2.85%      52.741ms         3.89%      72.163ms      46.437us        1.475s        88.14%        1.475s     949.389us           0 B           0 B       9.97 GB       9.97 GB          1554
                                  volta_sgemm_128x64_tn         0.00%       0.000us         0.00%       0.000us       0.000us     966.397ms        57.73%     966.397ms       1.941ms           0 B           0 B           0 B           0 B           498
                                 volta_sgemm_128x128_tn         0.00%       0.000us         0.00%       0.000us       0.000us     507.071ms        30.29%     507.071ms     510.132us           0 B           0 B           0 B           0 B           994
                     aten::scaled_dot_product_attention         0.18%       3.401ms         1.32%      24.467ms      97.091us       0.000us         0.00%      68.887ms     273.359us           0 B      -3.94 KB       1.11 GB           0 B           252
          aten::_scaled_dot_product_efficient_attention         0.15%       2.864ms         1.05%      19.441ms      77.148us       0.000us         0.00%      68.887ms     273.359us       3.94 KB           0 B       1.11 GB           0 B           252
                     aten::_efficient_attention_forward         0.29%       5.370ms         0.70%      12.936ms      51.335us      68.887ms         4.12%      68.887ms     273.359us       3.94 KB           0 B       1.11 GB           0 B           252
fmha_cutlassF_f32_aligned_64x64_rf_sm75(PyTorchMemEf...         0.00%       0.000us         0.00%       0.000us       0.000us      68.887ms         4.12%      68.887ms     276.653us           0 B           0 B           0 B           0 B           249
                                             aten::gelu         0.22%       4.029ms         0.34%       6.344ms      25.173us      39.383ms         2.35%      39.383ms     156.281us           0 B           0 B       4.43 GB       4.43 GB           252
void at::native::vectorized_elementwise_kernel<4, at...         0.00%       0.000us         0.00%       0.000us       0.000us      39.383ms         2.35%      39.383ms     158.164us           0 B           0 B           0 B           0 B           249
                                              aten::add         0.43%       7.976ms         0.63%      11.707ms      21.442us      31.164ms         1.86%      31.164ms      57.076us           0 B           0 B       2.31 GB       2.31 GB           546
void at::native::vectorized_elementwise_kernel<4, at...         0.00%       0.000us         0.00%       0.000us       0.000us      31.113ms         1.86%      31.113ms      60.064us           0 B           0 B           0 B           0 B           518
                                       aten::layer_norm         0.16%       2.876ms         1.44%      26.740ms      50.933us       0.000us         0.00%      28.006ms      53.344us           0 B           0 B       2.31 GB      -5.80 MB           525
                                aten::native_layer_norm         0.56%      10.315ms         1.29%      23.864ms      45.455us      28.006ms         1.67%      28.006ms      53.344us           0 B           0 B       2.31 GB           0 B           525
void at::native::(anonymous namespace)::vectorized_l...         0.00%       0.000us         0.00%       0.000us       0.000us      28.006ms         1.67%      28.006ms      54.065us           0 B           0 B           0 B           0 B           518
                                          aten::dropout         0.15%       2.817ms         1.49%      27.635ms      50.613us       0.000us         0.00%      25.208ms      46.168us           0 B           0 B       2.31 GB      -1.03 GB           546
                                   aten::native_dropout         0.50%       9.241ms         1.34%      24.818ms      45.454us      25.208ms         1.51%      25.208ms      46.168us           0 B           0 B       3.33 GB           0 B           546
void at::native::(anonymous namespace)::fused_dropou...         0.00%       0.000us         0.00%       0.000us       0.000us      25.208ms         1.51%      25.208ms      46.768us           0 B           0 B           0 B           0 B           539
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.853s
Self CUDA time total: 1.674s

\n================================================================================\n

Iteration: 100%|██████████| 109/109 [00:12<00:00,  8.74it/s]
11/23/2025 07:23:10 - INFO - finbert.utils -   *** Example ***
11/23/2025 07:23:10 - INFO - finbert.utils -   guid: validation-1
11/23/2025 07:23:10 - INFO - finbert.utils -   tokens: [CLS] our in - depth expertise extends to the fields of energy , industry , urban & mobility and water & environment [SEP]
11/23/2025 07:23:10 - INFO - finbert.utils -   input_ids: 101 2256 1999 1011 5995 11532 8908 2000 1996 4249 1997 2943 1010 3068 1010 3923 1004 12969 1998 2300 1004 4044 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:23:10 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:23:10 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:23:10 - INFO - finbert.utils -   label: neutral (id = 2)
11/23/2025 07:23:10 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 07:23:10 - INFO - finbert.finbert -     Num examples = 388
11/23/2025 07:23:10 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 07:23:10 - INFO - finbert.finbert -     Num steps = 48
Validating: 100%|██████████| 13/13 [00:01<00:00, 12.26it/s]

Validation losses: [0.8840945867391733]
No best model found

Iteration: 100%|██████████| 109/109 [00:19<00:00,  5.54it/s]
11/23/2025 07:23:31 - INFO - finbert.utils -   *** Example ***
11/23/2025 07:23:31 - INFO - finbert.utils -   guid: validation-1
11/23/2025 07:23:31 - INFO - finbert.utils -   tokens: [CLS] our in - depth expertise extends to the fields of energy , industry , urban & mobility and water & environment [SEP]
11/23/2025 07:23:31 - INFO - finbert.utils -   input_ids: 101 2256 1999 1011 5995 11532 8908 2000 1996 4249 1997 2943 1010 3068 1010 3923 1004 12969 1998 2300 1004 4044 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:23:31 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:23:31 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:23:31 - INFO - finbert.utils -   label: neutral (id = 2)
11/23/2025 07:23:31 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 07:23:31 - INFO - finbert.finbert -     Num examples = 388
11/23/2025 07:23:31 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 07:23:31 - INFO - finbert.finbert -     Num steps = 48
Validating: 100%|██████████| 13/13 [00:01<00:00, 11.81it/s]

Validation losses: [0.8840945867391733, 0.5758882806851313]

Iteration: 100%|██████████| 109/109 [00:24<00:00,  4.37it/s]
11/23/2025 07:23:58 - INFO - finbert.utils -   *** Example ***
11/23/2025 07:23:58 - INFO - finbert.utils -   guid: validation-1
11/23/2025 07:23:58 - INFO - finbert.utils -   tokens: [CLS] our in - depth expertise extends to the fields of energy , industry , urban & mobility and water & environment [SEP]
11/23/2025 07:23:58 - INFO - finbert.utils -   input_ids: 101 2256 1999 1011 5995 11532 8908 2000 1996 4249 1997 2943 1010 3068 1010 3923 1004 12969 1998 2300 1004 4044 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:23:58 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:23:58 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:23:58 - INFO - finbert.utils -   label: neutral (id = 2)
11/23/2025 07:23:58 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 07:23:58 - INFO - finbert.finbert -     Num examples = 388
11/23/2025 07:23:58 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 07:23:58 - INFO - finbert.finbert -     Num steps = 48
Validating: 100%|██████████| 13/13 [00:01<00:00, 12.71it/s]

Validation losses: [0.8840945867391733, 0.5758882806851313, 0.5057747524518234]

Iteration: 100%|██████████| 109/109 [00:27<00:00,  3.93it/s]
11/23/2025 07:24:27 - INFO - finbert.utils -   *** Example ***
11/23/2025 07:24:27 - INFO - finbert.utils -   guid: validation-1
11/23/2025 07:24:27 - INFO - finbert.utils -   tokens: [CLS] our in - depth expertise extends to the fields of energy , industry , urban & mobility and water & environment [SEP]
11/23/2025 07:24:27 - INFO - finbert.utils -   input_ids: 101 2256 1999 1011 5995 11532 8908 2000 1996 4249 1997 2943 1010 3068 1010 3923 1004 12969 1998 2300 1004 4044 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:24:27 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:24:27 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:24:27 - INFO - finbert.utils -   label: neutral (id = 2)
11/23/2025 07:24:27 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 07:24:27 - INFO - finbert.finbert -     Num examples = 388
11/23/2025 07:24:27 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 07:24:27 - INFO - finbert.finbert -     Num steps = 48
Validating: 100%|██████████| 13/13 [00:01<00:00, 12.55it/s]

Validation losses: [0.8840945867391733, 0.5758882806851313, 0.5057747524518234, 0.4857606108372028]

Epoch: 100%|██████████| 4/4 [01:32<00:00, 23.01s/it]

================================================================================
TRAINING COMPLETE
================================================================================

## 10. Load Model Variant

This cell loads the selected model variant using the modular registry.

In [22]:
# Load the selected model variant
model, variant = load_model_variant(SELECTED_VARIANT, cl_path)

print(f"\n✓ Ready for inference profiling with {SELECTED_VARIANT} variant")

Loading model variant: quantized_int8
Description: INT8 8-bit quantization via BitsAndBytes (3-4x compression)

11/23/2025 07:24:35 - INFO - accelerate.utils.modeling -   We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).

✓ Model loaded successfully
✓ Model size: 127.27 MB

✓ Ready for inference profiling with quantized_int8 variant

## 11. Profile Inference

Run inference profiling on the selected model variant.

### Profiling with Selected Variant

In [27]:
# Run profiled inference with the selected variant
results_df, metrics = profile_inference(
    model=model,
    text=TEST_TEXT,
    variant_name=SELECTED_VARIANT,
    use_gpu=USE_GPU,
    gpu_name=GPU_NAME
)

print("\n" + "="*80)
print("PREDICTION RESULTS")
print("="*80)
print(results_df[['sentence', 'prediction', 'sentiment_score']].to_string(index=False))
print("="*80)

11/23/2025 07:26:40 - INFO - finbert.utils -   *** Example ***
11/23/2025 07:26:40 - INFO - finbert.utils -   guid: 0
11/23/2025 07:26:40 - INFO - finbert.utils -   tokens: [CLS] later that day apple said it was rev ##ising down its earnings expectations in the fourth quarter of 2018 , largely because of lower sales and signs of economic weakness in china . [SEP]
11/23/2025 07:26:40 - INFO - finbert.utils -   input_ids: 101 2101 2008 2154 6207 2056 2009 2001 7065 9355 2091 2049 16565 10908 1999 1996 2959 4284 1997 2760 1010 4321 2138 1997 2896 4341 1998 5751 1997 3171 11251 1999 2859 1012 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:26:40 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:26:40 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 07:26:40 - INFO - finbert.utils -   label: None (id = 9090)

================================================================================
Device: cuda:0
GPU Name: Tesla T4
GPU Memory: 14.6 GB
================================================================================

ValueError: `.to` is not supported for `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.

## 12. Comparison Section (Not Applicable)

This section is not applicable as only the baseline variant is available.

In [ ]:
# Comparison functionality removed - only baseline variant is available
print("Only baseline variant is available. Comparison functionality has been removed.")

---

# LEGACY SECTIONS

The sections below contain the original notebook cells for reference. They have been superseded by the modular workflow above.

---

In [ ]:
def profiled_predict(text, model, write_to_csv=False, path=None, use_gpu=False, gpu_name='cuda:0', batch_size=5):
    """
    Predict sentiments with profiling instrumentation.
    
    Note: GPU-specific profiling (ProfilerActivity.CUDA) only works with NVIDIA CUDA devices.
    For MPS (Apple Silicon), only CPU profiling is available, though actual computation runs on GPU.
    """
    from nltk.tokenize import sent_tokenize
    from finbert.utils import InputExample, convert_examples_to_features, softmax, chunks, get_device
    from transformers import AutoTokenizer
    
    model.eval()
    tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
    
    # Use the device helper function for better device selection
    if use_gpu:
        device = get_device(no_cuda=False)
        # If user specified a specific CUDA device, use it
        if device.type == "cuda" and gpu_name.startswith("cuda:"):
            device = torch.device(gpu_name)
    else:
        device = torch.device("cpu")
    
    print(f"\\n{'='*80}")
    print(f"Starting Profiled Inference")
    print(f"Device: {device}")
    if device.type == "mps":
        print("Note: MPS profiling shows CPU time only. Actual GPU execution time not separately tracked.")
    print(f"{'='*80}\\n")
    
    label_list = ['positive', 'negative', 'neutral']
    label_dict = {0: 'positive', 1: 'negative', 2: 'neutral'}
    result = pd.DataFrame(columns=['sentence', 'logit', 'prediction', 'sentiment_score'])
    
    # Setup profiler - CUDA profiling only works with NVIDIA GPUs, not MPS
    activities = [ProfilerActivity.CPU]
    if device.type == "cuda":
        activities.append(ProfilerActivity.CUDA)
    
    with profile(
        activities=activities,
        record_shapes=True,
        profile_memory=True,
        with_stack=False
    ) as prof:
        
        with record_function("sentence_tokenization"):
            sentences = sent_tokenize(text)
        
        for batch in chunks(sentences, batch_size):
            with record_function("create_examples"):
                examples = [InputExample(str(i), sentence) for i, sentence in enumerate(batch)]
            
            with record_function("convert_to_features"):
                features = convert_examples_to_features(examples, label_list, 64, tokenizer)
            
            with record_function("prepare_tensors"):
                all_input_ids = torch.tensor([f.input_ids for f in features], dtype=torch.long).to(device)
                all_attention_mask = torch.tensor([f.attention_mask for f in features], dtype=torch.long).to(device)
                all_token_type_ids = torch.tensor([f.token_type_ids for f in features], dtype=torch.long).to(device)
            
            with torch.no_grad():
                with record_function("model_to_device"):
                    model = model.to(device)
                
                with record_function("inference_forward"):
                    logits = model(all_input_ids, all_attention_mask, all_token_type_ids)[0]
                
                with record_function("postprocess_results"):
                    logits = softmax(np.array(logits.cpu()))
                    sentiment_score = pd.Series(logits[:, 0] - logits[:, 1])
                    predictions = np.squeeze(np.argmax(logits, axis=1))
                    
                    batch_result = {'sentence': batch,
                                    'logit': list(logits),
                                    'prediction': predictions,
                                    'sentiment_score': sentiment_score}
                    
                    batch_result = pd.DataFrame(batch_result)
                    result = pd.concat([result, batch_result], ignore_index=True)
    
    # Print profiler results
    print(f"\\n{'='*80}")
    print("PROFILING RESULTS - Inference")
    print(f"{'='*80}\\n")
    
    print("\\nBy CPU Time:")
    print(prof.key_averages().table(sort_by="cpu_time_total", row_limit=20))
    
    if device.type == "cuda":
        print("\\nBy CUDA Time:")
        print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=20))
    
    print(f"\\n{'='*80}\\n")
    
    result['prediction'] = result.prediction.apply(lambda x: label_dict[x])
    if write_to_csv:
        result.to_csv(path, sep=',', index=False)
    
    return result

### Setting path variables

In [ ]:
cl_path = project_dir/'models'/'sentiment'
cl_data_path = project_dir/'data'/'sentiment_data'

###  Configuring training parameters

In [ ]:
# Clean the cl_path
try:
    shutil.rmtree(cl_path) 
except:
    pass

bertmodel = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', cache_dir=None, num_labels=3)

config = Config(   data_dir=cl_data_path,
                   bert_model=bertmodel,
                   num_train_epochs=6,
                   model_dir=cl_path,
                   max_seq_length = 48,
                   train_batch_size = 32,
                   learning_rate = 2e-5,
                   output_mode='classification',
                   warm_up_proportion=0.2,
                   local_rank=-1,
                   discriminate=True,
                   gradual_unfreeze=True)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
finbert = ProfiledFinBert(config)
finbert.base_model = 'bert-base-uncased'
finbert.config.discriminate=True
finbert.config.gradual_unfreeze=True

In [ ]:

finbert.prepare_model(label_list=['positive','negative','neutral'])

11/23/2025 05:51:06 - INFO - finbert.finbert -   device: cuda n_gpu: 1, distributed training: False, 16-bits training: False

## Fine-tune the model with profiling

In [ ]:
# Get the training examples
train_data = finbert.get_data('train')

In [ ]:
model = finbert.create_the_model()

### Training with Profiling

This will profile the first 20 steps of the first epoch, then continue with normal training.

In [ ]:
trained_model = finbert.train(train_examples = train_data, model = model)

11/23/2025 05:51:19 - INFO - finbert.utils -   *** Example ***
11/23/2025 05:51:19 - INFO - finbert.utils -   guid: train-1
11/23/2025 05:51:19 - INFO - finbert.utils -   tokens: [CLS] after the reporting period , bio ##tie north american licensing partner so ##max ##on pharmaceuticals announced positive results with na ##lm ##efe ##ne in a pilot phase 2 clinical trial for smoking ce ##ssa ##tion [SEP]
11/23/2025 05:51:19 - INFO - finbert.utils -   input_ids: 101 2044 1996 7316 2558 1010 16012 9515 2167 2137 13202 4256 2061 17848 2239 24797 2623 3893 3463 2007 6583 13728 27235 2638 1999 1037 4405 4403 1016 6612 3979 2005 9422 8292 11488 3508 102 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:51:19 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:51:19 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:51:19 - INFO - finbert.utils -   label: positive (id = 0)

11/23/2025 05:51:20 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 05:51:20 - INFO - finbert.finbert -     Num examples = 3488
11/23/2025 05:51:20 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 05:51:20 - INFO - finbert.finbert -     Num steps = 72

\n================================================================================
Starting Profiled Training
Device: cuda
Profiling activities: [<ProfilerActivity.CPU: 0>, <ProfilerActivity.CUDA: 2>]
================================================================================\n

Iteration:  18%|█▊        | 20/109 [00:01<00:07, 11.53it/s]
Epoch:   0%|          | 0/6 [00:01<?, ?it/s]

\n================================================================================
Profiling complete for first epoch (20 steps)
Continuing full training without profiling...
================================================================================\n
\n================================================================================
PROFILING RESULTS - Training
================================================================================\n
\nBy CPU Time:
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                       loss_calculation         0.26%       4.399ms        74.95%        1.287s      61.298ms       0.000us         0.00%     152.060us       7.241us           0 B           0 B      22.00 KB     -20.00 KB            21
                                               aten::to         0.05%     800.696us        74.89%        1.286s       3.805ms       0.000us         0.00%     479.610us       1.419us           0 B           0 B       8.15 MB           0 B           338
                                         aten::_to_copy         0.07%       1.216ms        74.84%        1.285s       7.651ms       0.000us         0.00%     479.610us       2.855us           0 B           0 B       8.15 MB           0 B           168
                                            aten::copy_         0.10%       1.673ms        74.73%        1.283s       6.791ms     547.353us         0.04%     547.353us       2.896us           0 B           0 B           0 B           0 B           189
                                  cudaStreamSynchronize        74.50%        1.280s        74.50%        1.280s       7.617ms       0.000us         0.00%       0.000us       0.000us           0 B           0 B           0 B           0 B           168
                                           forward_pass         5.56%      95.485ms        17.91%     307.641ms      14.650ms       0.000us         0.00%        1.507s      71.761ms           0 B         -84 B       1.97 MB     -22.64 GB            21
                                           aten::linear         0.79%      13.636ms         5.86%     100.618ms      64.748us       0.000us         0.00%        1.320s     849.647us           0 B           0 B       9.97 GB           0 B          1554
                                            aten::addmm         2.76%      47.410ms         3.79%      65.097ms      41.890us        1.320s        87.44%        1.320s     849.647us           0 B           0 B       9.97 GB       9.97 GB          1554
                                         optimizer_step         1.20%      20.598ms         2.98%      51.260ms       2.441ms       0.000us         0.00%       2.091ms      99.568us           8 B           0 B    -180.50 KB     -84.00 KB            21
                                       cudaLaunchKernel         2.23%      38.307ms         2.23%      38.307ms       8.284us       0.000us         0.00%       0.000us       0.000us           0 B           0 B           0 B           0 B          4624
enumerate(DataLoader)#_SingleProcessDataLoaderIter._...         0.86%      14.745ms         2.12%      36.401ms       1.733ms       0.000us         0.00%       0.000us       0.000us     766.50 KB     -27.26 KB           0 B           0 B            21
                                          aten::dropout         0.15%       2.588ms         1.49%      25.641ms      46.962us       0.000us         0.00%      24.862ms      45.536us           0 B           0 B       2.31 GB      -1.03 GB           546
                                       aten::layer_norm         0.16%       2.767ms         1.46%      24.998ms      47.616us       0.000us         0.00%      25.824ms      49.189us           0 B           0 B       2.31 GB      -5.82 MB           525
                     aten::scaled_dot_product_attention         0.20%       3.380ms         1.39%      23.855ms      94.664us       0.000us         0.00%      63.274ms     251.087us           0 B      -3.94 KB       1.11 GB           0 B           252
                                   aten::native_dropout         0.50%       8.628ms         1.34%      23.053ms      42.222us      24.862ms         1.65%      24.862ms      45.536us           0 B           0 B       3.33 GB           0 B           546
                              Optimizer.step#AdamW.step         0.86%      14.755ms         1.33%      22.800ms       1.086ms       0.000us         0.00%       1.380ms      65.691us           8 B        -168 B      19.00 KB    -199.50 KB            21
                                aten::native_layer_norm         0.57%       9.752ms         1.29%      22.231ms      42.344us      25.824ms         1.71%      25.824ms      49.189us           0 B           0 B       2.31 GB           0 B           525
                                          backward_pass         1.04%      17.928ms         1.11%      18.981ms     903.867us       0.000us         0.00%      42.273us       2.013us           0 B           0 B      -1.79 MB      -1.80 MB            21
          aten::_scaled_dot_product_efficient_attention         0.16%       2.798ms         1.10%      18.869ms      74.876us       0.000us         0.00%      63.274ms     251.087us       3.94 KB           0 B       1.11 GB           0 B           252
                                        aten::transpose         0.65%      11.112ms         0.93%      16.025ms       4.411us       0.000us         0.00%       0.000us       0.000us           0 B           0 B           0 B           0 B          3633
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.717s
Self CUDA time total: 1.510s

\nBy CUDA Time:
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                           forward_pass         0.00%       0.000us         0.00%       0.000us       0.000us        1.526s       101.06%        1.526s      72.666ms           0 B           0 B           0 B           0 B            21
                                           forward_pass         5.56%      95.485ms        17.91%     307.641ms      14.650ms       0.000us         0.00%        1.507s      71.761ms           0 B         -84 B       1.97 MB     -22.64 GB            21
                                           aten::linear         0.79%      13.636ms         5.86%     100.618ms      64.748us       0.000us         0.00%        1.320s     849.647us           0 B           0 B       9.97 GB           0 B          1554
                                            aten::addmm         2.76%      47.410ms         3.79%      65.097ms      41.890us        1.320s        87.44%        1.320s     849.647us           0 B           0 B       9.97 GB       9.97 GB          1554
                                  volta_sgemm_128x64_tn         0.00%       0.000us         0.00%       0.000us       0.000us     863.525ms        57.19%     863.525ms       1.755ms           0 B           0 B           0 B           0 B           492
                                 volta_sgemm_128x128_tn         0.00%       0.000us         0.00%       0.000us       0.000us     455.036ms        30.14%     455.036ms     462.435us           0 B           0 B           0 B           0 B           984
                     aten::scaled_dot_product_attention         0.20%       3.380ms         1.39%      23.855ms      94.664us       0.000us         0.00%      63.274ms     251.087us           0 B      -3.94 KB       1.11 GB           0 B           252
          aten::_scaled_dot_product_efficient_attention         0.16%       2.798ms         1.10%      18.869ms      74.876us       0.000us         0.00%      63.274ms     251.087us       3.94 KB           0 B       1.11 GB           0 B           252
                     aten::_efficient_attention_forward         0.31%       5.321ms         0.72%      12.444ms      49.380us      63.274ms         4.19%      63.274ms     251.087us       3.94 KB           0 B       1.11 GB           0 B           252
fmha_cutlassF_f32_aligned_64x64_rf_sm75(PyTorchMemEf...         0.00%       0.000us         0.00%       0.000us       0.000us      63.274ms         4.19%      63.274ms     257.211us           0 B           0 B           0 B           0 B           246
                                             aten::gelu         0.22%       3.803ms         0.34%       5.859ms      23.250us      39.313ms         2.60%      39.313ms     156.005us           0 B           0 B       4.43 GB       4.43 GB           252
void at::native::vectorized_elementwise_kernel<4, at...         0.00%       0.000us         0.00%       0.000us       0.000us      39.313ms         2.60%      39.313ms     159.810us           0 B           0 B           0 B           0 B           246
                                              aten::add         0.45%       7.670ms         0.66%      11.401ms      20.880us      30.762ms         2.04%      30.762ms      56.340us           0 B           0 B       2.31 GB       2.31 GB           546
void at::native::vectorized_elementwise_kernel<4, at...         0.00%       0.000us         0.00%       0.000us       0.000us      30.715ms         2.03%      30.715ms      59.991us           0 B           0 B           0 B           0 B           512
                                       aten::layer_norm         0.16%       2.767ms         1.46%      24.998ms      47.616us       0.000us         0.00%      25.824ms      49.189us           0 B           0 B       2.31 GB      -5.82 MB           525
                                aten::native_layer_norm         0.57%       9.752ms         1.29%      22.231ms      42.344us      25.824ms         1.71%      25.824ms      49.189us           0 B           0 B       2.31 GB           0 B           525
void at::native::(anonymous namespace)::vectorized_l...         0.00%       0.000us         0.00%       0.000us       0.000us      25.824ms         1.71%      25.824ms      50.438us           0 B           0 B           0 B           0 B           512
                                          aten::dropout         0.15%       2.588ms         1.49%      25.641ms      46.962us       0.000us         0.00%      24.862ms      45.536us           0 B           0 B       2.31 GB      -1.03 GB           546
                                   aten::native_dropout         0.50%       8.628ms         1.34%      23.053ms      42.222us      24.862ms         1.65%      24.862ms      45.536us           0 B           0 B       3.33 GB           0 B           546
void at::native::(anonymous namespace)::fused_dropou...         0.00%       0.000us         0.00%       0.000us       0.000us      24.862ms         1.65%      24.862ms      46.646us           0 B           0 B           0 B           0 B           533
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.717s
Self CUDA time total: 1.510s

\n================================================================================\n

Iteration: 100%|██████████| 109/109 [00:11<00:00,  9.68it/s]
11/23/2025 05:51:42 - INFO - finbert.utils -   *** Example ***
11/23/2025 05:51:42 - INFO - finbert.utils -   guid: validation-1
11/23/2025 05:51:42 - INFO - finbert.utils -   tokens: [CLS] our in - depth expertise extends to the fields of energy , industry , urban & mobility and water & environment [SEP]
11/23/2025 05:51:42 - INFO - finbert.utils -   input_ids: 101 2256 1999 1011 5995 11532 8908 2000 1996 4249 1997 2943 1010 3068 1010 3923 1004 12969 1998 2300 1004 4044 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:51:42 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:51:42 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:51:42 - INFO - finbert.utils -   label: neutral (id = 2)
11/23/2025 05:51:42 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 05:51:42 - INFO - finbert.finbert -     Num examples = 388
11/23/2025 05:51:42 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 05:51:42 - INFO - finbert.finbert -     Num steps = 72
Validating: 100%|██████████| 13/13 [00:00<00:00, 13.94it/s]

Validation losses: [0.9521260765882639]
No best model found

Iteration: 100%|██████████| 109/109 [00:17<00:00,  6.25it/s]
11/23/2025 05:52:01 - INFO - finbert.utils -   *** Example ***
11/23/2025 05:52:01 - INFO - finbert.utils -   guid: validation-1
11/23/2025 05:52:01 - INFO - finbert.utils -   tokens: [CLS] our in - depth expertise extends to the fields of energy , industry , urban & mobility and water & environment [SEP]
11/23/2025 05:52:01 - INFO - finbert.utils -   input_ids: 101 2256 1999 1011 5995 11532 8908 2000 1996 4249 1997 2943 1010 3068 1010 3923 1004 12969 1998 2300 1004 4044 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:52:01 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:52:01 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:52:01 - INFO - finbert.utils -   label: neutral (id = 2)
11/23/2025 05:52:01 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 05:52:01 - INFO - finbert.finbert -     Num examples = 388
11/23/2025 05:52:01 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 05:52:01 - INFO - finbert.finbert -     Num steps = 72
Validating: 100%|██████████| 13/13 [00:00<00:00, 13.76it/s]

Validation losses: [0.9521260765882639, 0.5104634532561669]

Iteration: 100%|██████████| 109/109 [00:23<00:00,  4.67it/s]
11/23/2025 05:52:26 - INFO - finbert.utils -   *** Example ***
11/23/2025 05:52:26 - INFO - finbert.utils -   guid: validation-1
11/23/2025 05:52:26 - INFO - finbert.utils -   tokens: [CLS] our in - depth expertise extends to the fields of energy , industry , urban & mobility and water & environment [SEP]
11/23/2025 05:52:26 - INFO - finbert.utils -   input_ids: 101 2256 1999 1011 5995 11532 8908 2000 1996 4249 1997 2943 1010 3068 1010 3923 1004 12969 1998 2300 1004 4044 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:52:26 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:52:26 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:52:26 - INFO - finbert.utils -   label: neutral (id = 2)
11/23/2025 05:52:26 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 05:52:26 - INFO - finbert.finbert -     Num examples = 388
11/23/2025 05:52:26 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 05:52:26 - INFO - finbert.finbert -     Num steps = 72
Validating: 100%|██████████| 13/13 [00:00<00:00, 13.48it/s]

Validation losses: [0.9521260765882639, 0.5104634532561669, 0.4623632373718115]

Iteration: 100%|██████████| 109/109 [00:26<00:00,  4.07it/s]
11/23/2025 05:52:54 - INFO - finbert.utils -   *** Example ***
11/23/2025 05:52:54 - INFO - finbert.utils -   guid: validation-1
11/23/2025 05:52:54 - INFO - finbert.utils -   tokens: [CLS] our in - depth expertise extends to the fields of energy , industry , urban & mobility and water & environment [SEP]
11/23/2025 05:52:54 - INFO - finbert.utils -   input_ids: 101 2256 1999 1011 5995 11532 8908 2000 1996 4249 1997 2943 1010 3068 1010 3923 1004 12969 1998 2300 1004 4044 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:52:54 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:52:54 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:52:54 - INFO - finbert.utils -   label: neutral (id = 2)
11/23/2025 05:52:54 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 05:52:54 - INFO - finbert.finbert -     Num examples = 388
11/23/2025 05:52:54 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 05:52:54 - INFO - finbert.finbert -     Num steps = 72
Validating: 100%|██████████| 13/13 [00:00<00:00, 13.05it/s]

Validation losses: [0.9521260765882639, 0.5104634532561669, 0.4623632373718115, 0.4043929324700282]

Iteration: 100%|██████████| 109/109 [00:27<00:00,  4.03it/s]
11/23/2025 05:53:23 - INFO - finbert.utils -   *** Example ***
11/23/2025 05:53:23 - INFO - finbert.utils -   guid: validation-1
11/23/2025 05:53:23 - INFO - finbert.utils -   tokens: [CLS] our in - depth expertise extends to the fields of energy , industry , urban & mobility and water & environment [SEP]
11/23/2025 05:53:23 - INFO - finbert.utils -   input_ids: 101 2256 1999 1011 5995 11532 8908 2000 1996 4249 1997 2943 1010 3068 1010 3923 1004 12969 1998 2300 1004 4044 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:53:23 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:53:23 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:53:23 - INFO - finbert.utils -   label: neutral (id = 2)
11/23/2025 05:53:23 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 05:53:23 - INFO - finbert.finbert -     Num examples = 388
11/23/2025 05:53:23 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 05:53:23 - INFO - finbert.finbert -     Num steps = 72
Validating: 100%|██████████| 13/13 [00:00<00:00, 13.01it/s]

Validation losses: [0.9521260765882639, 0.5104634532561669, 0.4623632373718115, 0.4043929324700282, 0.37776797780623805]

Iteration: 100%|██████████| 109/109 [00:27<00:00,  4.01it/s]
11/23/2025 05:53:52 - INFO - finbert.utils -   *** Example ***
11/23/2025 05:53:52 - INFO - finbert.utils -   guid: validation-1
11/23/2025 05:53:52 - INFO - finbert.utils -   tokens: [CLS] our in - depth expertise extends to the fields of energy , industry , urban & mobility and water & environment [SEP]
11/23/2025 05:53:52 - INFO - finbert.utils -   input_ids: 101 2256 1999 1011 5995 11532 8908 2000 1996 4249 1997 2943 1010 3068 1010 3923 1004 12969 1998 2300 1004 4044 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:53:52 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:53:52 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 05:53:52 - INFO - finbert.utils -   label: neutral (id = 2)
11/23/2025 05:53:52 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 05:53:52 - INFO - finbert.finbert -     Num examples = 388
11/23/2025 05:53:52 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 05:53:52 - INFO - finbert.finbert -     Num steps = 72
Validating: 100%|██████████| 13/13 [00:00<00:00, 13.12it/s]

Validation losses: [0.9521260765882639, 0.5104634532561669, 0.4623632373718115, 0.4043929324700282, 0.37776797780623805, 0.37106514779421]

Epoch: 100%|██████████| 6/6 [02:23<00:00, 23.90s/it]

## Test the model

In [ ]:
test_data = finbert.get_data('test')

In [ ]:
results = finbert.evaluate(examples=test_data, model=trained_model)

11/23/2025 04:28:50 - INFO - finbert.utils -   *** Example ***
11/23/2025 04:28:50 - INFO - finbert.utils -   guid: test-1
11/23/2025 04:28:50 - INFO - finbert.utils -   tokens: [CLS] the bristol port company has sealed a one million pound contract with cooper specialised handling to supply it with four 45 - ton ##ne , custom ##ised reach stack ##ers from ko ##ne ##cr ##ane ##s [SEP]
11/23/2025 04:28:50 - INFO - finbert.utils -   input_ids: 101 1996 7067 3417 2194 2038 10203 1037 2028 2454 9044 3206 2007 6201 17009 8304 2000 4425 2009 2007 2176 3429 1011 10228 2638 1010 7661 5084 3362 9991 2545 2013 12849 2638 26775 7231 2015 102 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:28:50 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:28:50 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:28:50 - INFO - finbert.utils -   label: positive (id = 0)
11/23/2025 04:28:50 - INFO - finbert.finbert -   ***** Loading data *****
11/23/2025 04:28:50 - INFO - finbert.finbert -     Num examples = 970
11/23/2025 04:28:50 - INFO - finbert.finbert -     Batch size = 32
11/23/2025 04:28:50 - INFO - finbert.finbert -     Num steps = 120
11/23/2025 04:28:50 - INFO - finbert.finbert -   ***** Running evaluation *****
11/23/2025 04:28:50 - INFO - finbert.finbert -     Num examples = 970
11/23/2025 04:28:50 - INFO - finbert.finbert -     Batch size = 32

Testing: 100%|██████████| 31/31 [00:02<00:00, 11.76it/s]

### Prepare the classification report

In [ ]:
def report(df, cols=['label','prediction','logits']):
    cs = CrossEntropyLoss(weight=finbert.class_weights)
    loss = cs(torch.tensor(list(df[cols[2]])),torch.tensor(list(df[cols[0]])))
    print("Loss:{0:.2f}".format(loss))
    print("Accuracy:{0:.2f}".format((df[cols[0]] == df[cols[1]]).sum() / df.shape[0]) )
    print("\\nClassification Report:")
    print(classification_report(df[cols[0]], df[cols[1]]))

In [ ]:
results['prediction'] = results.predictions.apply(lambda x: np.argmax(x,axis=0))

In [ ]:
report(results,cols=['labels','prediction','predictions'])

Loss:0.48
Accuracy:0.79
\nClassification Report:
              precision    recall  f1-score   support

           0       0.68      0.79      0.73       267
           1       0.69      0.94      0.79       128
           2       0.90      0.76      0.83       575

    accuracy                           0.79       970
   macro avg       0.76      0.83      0.78       970
weighted avg       0.81      0.79      0.80       970

/var/tmp/ipykernel_78746/562382605.py:3: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:253.)
  loss = cs(torch.tensor(list(df[cols[2]])),torch.tensor(list(df[cols[0]])))

## Get predictions with profiling

In [ ]:
text = "Later that day Apple said it was revising down its earnings expectations in \
the fourth quarter of 2018, largely because of lower sales and signs of economic weakness in China. \
The news rapidly infected financial markets. Apple's share price fell by around 7% in after-hours \
trading and the decline was extended to more than 10% when the market opened. The dollar fell \
by 3.7% against the yen in a matter of minutes after the announcement, before rapidly recovering \
some ground. Asian stockmarkets closed down on January 3rd and European ones opened lower. \
Yields on government bonds fell as investors fled to the traditional haven in a market storm."

In [ ]:
cl_path = project_dir/'models'/'sentiment'
model = AutoModelForSequenceClassification.from_pretrained(cl_path, cache_dir=None, num_labels=3)

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /home/tfs2123/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/tfs2123/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
result = profiled_predict(text, model, use_gpu=True, gpu_name='cuda:0')

11/23/2025 04:30:15 - INFO - finbert.utils -   *** Example ***
11/23/2025 04:30:15 - INFO - finbert.utils -   guid: 0
11/23/2025 04:30:15 - INFO - finbert.utils -   tokens: [CLS] later that day apple said it was rev ##ising down its earnings expectations in the fourth quarter of 2018 , largely because of lower sales and signs of economic weakness in china . [SEP]
11/23/2025 04:30:15 - INFO - finbert.utils -   input_ids: 101 2101 2008 2154 6207 2056 2009 2001 7065 9355 2091 2049 16565 10908 1999 1996 2959 4284 1997 2760 1010 4321 2138 1997 2896 4341 1998 5751 1997 3171 11251 1999 2859 1012 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:30:15 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:30:15 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:30:15 - INFO - finbert.utils -   label: None (id = 9090)
[W1123 04:30:15.959346523 CPUAllocator.cpp:245] Memory block of unknown size was allocated before the profiling started, profiler results will not include the deallocation event
/var/tmp/ipykernel_78746/3401394247.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result = pd.concat([result, batch_result], ignore_index=True)
11/23/2025 04:30:15 - INFO - finbert.utils -   *** Example ***
11/23/2025 04:30:15 - INFO - finbert.utils -   guid: 0
11/23/2025 04:30:15 - INFO - finbert.utils -   tokens: [CLS] yields on government bonds fell as investors fled to the traditional haven in a market storm . [SEP]
11/23/2025 04:30:15 - INFO - finbert.utils -   input_ids: 101 16189 2006 2231 9547 3062 2004 9387 6783 2000 1996 3151 4033 1999 1037 3006 4040 1012 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:30:15 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:30:15 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:30:15 - INFO - finbert.utils -   label: None (id = 9090)

\n================================================================================
Starting Profiled Inference
Device: cuda:0
================================================================================\n
\n================================================================================
PROFILING RESULTS - Inference
================================================================================\n
\nBy CPU Time:
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                        model_to_device        15.33%      36.174ms        68.41%     161.410ms      80.705ms       0.000us         0.00%      96.494ms      48.247ms    -417.73 MB    -417.73 MB     418.74 MB           0 B             2
                                               aten::to         0.27%     636.330us        58.39%     137.762ms     321.873us       0.000us         0.00%      96.540ms     225.562us          72 B           0 B     418.86 MB           0 B           428
                                         aten::_to_copy         0.72%       1.711ms        58.12%     137.125ms     637.793us       0.000us         0.00%      96.540ms     449.025us          72 B           0 B     418.86 MB           0 B           215
                                            aten::copy_         0.83%       1.965ms        56.60%     133.543ms     615.407us      96.545ms        73.34%      96.546ms     444.913us           0 B           0 B           0 B           0 B           217
                                        cudaMemcpyAsync        53.25%     125.653ms        53.25%     125.653ms     584.432us       0.000us         0.00%       0.000us       0.000us           0 B           0 B           0 B           0 B           215
                                      inference_forward         4.54%      10.702ms        20.07%      47.346ms      23.673ms       0.000us         0.00%      35.250ms      17.625ms           0 B          -8 B       1.00 KB    -248.22 MB             2
                                           aten::linear         0.61%       1.443ms        11.50%      27.134ms     183.340us       0.000us         0.00%      32.221ms     217.711us           0 B           0 B     121.52 MB           0 B           148
                                            aten::addmm         3.78%       8.924ms         9.94%      23.458ms     158.501us      32.109ms        24.39%      32.221ms     217.711us           0 B           0 B     121.52 MB     121.52 MB           148
                                    postprocess_results         1.08%       2.552ms         6.08%      14.348ms       7.174ms       0.000us         0.00%       4.256us       2.128us           0 B         -72 B      -1.00 KB      -1.00 KB             2
cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFla...         0.03%      60.630us         5.07%      11.968ms       2.992ms       0.000us         0.00%     103.357us      25.839us           0 B           0 B           0 B           0 B             4
                       Runtime Triggered Module Loading         4.96%      11.699ms         4.96%      11.699ms       2.925ms      47.550us         0.04%      47.550us      11.887us           0 B           0 B           0 B           0 B             4
                                    convert_to_features         4.24%      10.008ms         4.24%      10.008ms       5.004ms       0.000us         0.00%       0.000us       0.000us           0 B           0 B           0 B           0 B             2
                                  cudaStreamSynchronize         2.19%       5.166ms         2.19%       5.166ms      24.254us       0.000us         0.00%       0.000us       0.000us           0 B           0 B           0 B           0 B           213
                                       cudaLaunchKernel         1.40%       3.305ms         1.41%       3.322ms       9.052us       0.000us         0.00%       8.767us       0.024us           0 B           0 B           0 B           0 B           367
                     aten::scaled_dot_product_attention         0.16%     373.009us         1.12%       2.646ms     110.251us       0.000us         0.00%       1.363ms      56.795us           0 B        -384 B      13.50 MB           0 B            24
                                       aten::layer_norm         0.12%     280.237us         1.09%       2.574ms      51.472us       0.000us         0.00%     770.007us      15.400us           0 B           0 B      28.13 MB     -99.00 KB            50
                                        prepare_tensors         0.50%       1.183ms         1.03%       2.420ms       1.210ms       0.000us         0.00%       6.530us       3.265us           0 B      -9.00 KB       1.50 KB      -7.50 KB             2
                                aten::native_layer_norm         0.42%     987.485us         0.97%       2.293ms      45.867us     770.007us         0.58%     770.007us      15.400us           0 B           0 B      28.22 MB           0 B            50
          aten::_scaled_dot_product_efficient_attention         0.14%     329.102us         0.90%       2.122ms      88.405us       0.000us         0.00%       1.363ms      56.795us         384 B           0 B      13.50 MB           0 B            24
                                    aten::empty_strided         0.81%       1.919ms         0.81%       1.919ms       8.925us       0.000us         0.00%       0.000us       0.000us          72 B          72 B     418.86 MB     418.86 MB           215
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 235.954ms
Self CUDA time total: 131.641ms

\nBy CUDA Time:
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                        model_to_device         0.00%       0.000us         0.00%       0.000us       0.000us     131.878ms       100.18%     131.878ms     131.878ms           0 B           0 B           0 B           0 B             1
                                            aten::copy_         0.83%       1.965ms        56.60%     133.543ms     615.407us      96.545ms        73.34%      96.546ms     444.913us           0 B           0 B           0 B           0 B           217
                                               aten::to         0.27%     636.330us        58.39%     137.762ms     321.873us       0.000us         0.00%      96.540ms     225.562us          72 B           0 B     418.86 MB           0 B           428
                                         aten::_to_copy         0.72%       1.711ms        58.12%     137.125ms     637.793us       0.000us         0.00%      96.540ms     449.025us          72 B           0 B     418.86 MB           0 B           215
                       Memcpy HtoD (Pageable -> Device)         0.00%       0.000us         0.00%       0.000us       0.000us      96.499ms        73.30%      96.499ms     461.720us           0 B           0 B           0 B           0 B           209
                                        model_to_device        15.33%      36.174ms        68.41%     161.410ms      80.705ms       0.000us         0.00%      96.494ms      48.247ms    -417.73 MB    -417.73 MB     418.74 MB           0 B             2
                                      inference_forward         0.00%       0.000us         0.00%       0.000us       0.000us      58.242ms        44.24%      58.242ms      29.121ms           0 B           0 B           0 B           0 B             2
                                      inference_forward         4.54%      10.702ms        20.07%      47.346ms      23.673ms       0.000us         0.00%      35.250ms      17.625ms           0 B          -8 B       1.00 KB    -248.22 MB             2
                                           aten::linear         0.61%       1.443ms        11.50%      27.134ms     183.340us       0.000us         0.00%      32.221ms     217.711us           0 B           0 B     121.52 MB           0 B           148
                                            aten::addmm         3.78%       8.924ms         9.94%      23.458ms     158.501us      32.109ms        24.39%      32.221ms     217.711us           0 B           0 B     121.52 MB     121.52 MB           148
                                  volta_sgemm_128x64_tn         0.00%       0.000us         0.00%       0.000us       0.000us      31.541ms        23.96%      31.541ms     219.036us           0 B           0 B           0 B           0 B           144
                     aten::scaled_dot_product_attention         0.16%     373.009us         1.12%       2.646ms     110.251us       0.000us         0.00%       1.363ms      56.795us           0 B        -384 B      13.50 MB           0 B            24
          aten::_scaled_dot_product_efficient_attention         0.14%     329.102us         0.90%       2.122ms      88.405us       0.000us         0.00%       1.363ms      56.795us         384 B           0 B      13.50 MB           0 B            24
                     aten::_efficient_attention_forward         0.18%     423.029us         0.62%       1.456ms      60.661us       1.363ms         1.04%       1.363ms      56.795us         384 B           0 B      13.50 MB           0 B            24
fmha_cutlassF_f32_aligned_64x64_rf_sm75(PyTorchMemEf...         0.00%       0.000us         0.00%       0.000us       0.000us       1.363ms         1.04%       1.363ms      56.795us           0 B           0 B           0 B           0 B            24
                                       aten::layer_norm         0.12%     280.237us         1.09%       2.574ms      51.472us       0.000us         0.00%     770.007us      15.400us           0 B           0 B      28.13 MB     -99.00 KB            50
                                aten::native_layer_norm         0.42%     987.485us         0.97%       2.293ms      45.867us     770.007us         0.58%     770.007us      15.400us           0 B           0 B      28.22 MB           0 B            50
void at::native::(anonymous namespace)::vectorized_l...         0.00%       0.000us         0.00%       0.000us       0.000us     770.007us         0.58%     770.007us      15.400us           0 B           0 B           0 B           0 B            50
                                             aten::gelu         0.17%     392.488us         0.26%     615.190us      25.633us     431.323us         0.33%     431.323us      17.972us           0 B           0 B      54.00 MB      54.00 MB            24
void at::native::vectorized_elementwise_kernel<4, at...         0.00%       0.000us         0.00%       0.000us       0.000us     431.323us         0.33%     431.323us      17.972us           0 B           0 B           0 B           0 B            24
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 235.954ms
Self CUDA time total: 131.641ms

\n================================================================================\n

In [ ]:
blob = TextBlob(text)
result['textblob_prediction'] = [sentence.sentiment.polarity for sentence in blob.sentences]
result.head()

,sentence,logit,prediction,sentiment_score,textblob_prediction
0,"Later that day Apple said it was revising down its earnings expectations in the fourth quarter of 2018, largely because of lower sales and signs of economic weakness in China.","[0.080251485, 0.8814244, 0.038324043]",negative,-0.801173,0.051746
1,The news rapidly infected financial markets.,"[0.10354158, 0.80237246, 0.094086014]",negative,-0.698831,0.000000
2,Apple's share price fell by around 7% in after-hours trading and the decline was extended to more than 10% when the market opened.,"[0.071600966, 0.89696515, 0.031433992]",negative,-0.825364,0.500000
3,"The dollar fell by 3.7% against the yen in a matter of minutes after the announcement, before rapidly recovering some ground.","[0.10870564, 0.8646172, 0.026677087]",negative,-0.755912,0.000000
4,Asian stockmarkets closed down on January 3rd and European ones opened lower.,"[0.060098637, 0.8936129, 0.0462884]",negative,-0.833514,-0.051111

In [ ]:
print(f'Average sentiment is %.2f.' % (result.sentiment_score.mean()))

Average sentiment is -0.79.

## Second example with profiling

In [ ]:
text2 = "Shares in the spin-off of South African e-commerce group Naspers surged more than 25% \
in the first minutes of their market debut in Amsterdam on Wednesday. Bob van Dijk, CEO of \
Naspers and Prosus Group poses at Amsterdam's stock exchange, as Prosus begins trading on the \
Euronext stock exchange in Amsterdam, Netherlands, September 11, 2019. REUTERS/Piroschka van de Wouw \
Prosus comprises Naspers' global empire of consumer internet assets, with the jewel in the crown a \
31% stake in Chinese tech titan Tencent. There is 'way more demand than is even available, so that's \
good,' said the CEO of Euronext Amsterdam, Maurice van Tilburg. 'It's going to be an interesting \
hour of trade after opening this morning.' Euronext had given an indicative price of 58.70 euros \
per share for Prosus, implying a market value of 95.3 billion euros ($105 billion). The shares \
jumped to 76 euros on opening and were trading at 75 euros at 0719 GMT."

In [ ]:
result2 = profiled_predict(text2, model, use_gpu=True, gpu_name='cuda:0')
blob = TextBlob(text2)
result2['textblob_prediction'] = [sentence.sentiment.polarity for sentence in blob.sentences]

11/23/2025 04:28:58 - INFO - finbert.utils -   *** Example ***
11/23/2025 04:28:58 - INFO - finbert.utils -   guid: 0
11/23/2025 04:28:58 - INFO - finbert.utils -   tokens: [CLS] shares in the spin - off of south african e - commerce group nas ##pers surged more than 25 % in the first minutes of their market debut in amsterdam on wednesday . [SEP]
11/23/2025 04:28:58 - INFO - finbert.utils -   input_ids: 101 6661 1999 1996 6714 1011 2125 1997 2148 3060 1041 1011 6236 2177 17235 7347 18852 2062 2084 2423 1003 1999 1996 2034 2781 1997 2037 3006 2834 1999 7598 2006 9317 1012 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:28:58 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:28:58 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:28:58 - INFO - finbert.utils -   label: None (id = 9090)
/var/tmp/ipykernel_78746/3401394247.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result = pd.concat([result, batch_result], ignore_index=True)
11/23/2025 04:28:58 - INFO - finbert.utils -   *** Example ***
11/23/2025 04:28:58 - INFO - finbert.utils -   guid: 0
11/23/2025 04:28:58 - INFO - finbert.utils -   tokens: [CLS] euro ##ne ##xt had given an indicative price of 58 . 70 euros per share for pro ##sus , implying a market value of 95 . 3 billion euros ( $ 105 billion ) . [SEP]
11/23/2025 04:28:58 - INFO - finbert.utils -   input_ids: 101 9944 2638 18413 2018 2445 2019 24668 3976 1997 5388 1012 3963 19329 2566 3745 2005 4013 13203 1010 20242 1037 3006 3643 1997 5345 1012 1017 4551 19329 1006 1002 8746 4551 1007 1012 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:28:58 - INFO - finbert.utils -   attention_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:28:58 - INFO - finbert.utils -   token_type_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
11/23/2025 04:28:58 - INFO - finbert.utils -   label: None (id = 9090)

\n================================================================================
Starting Profiled Inference
Device: cpu
================================================================================\n
\n================================================================================
PROFILING RESULTS - Inference
================================================================================\n
\nBy CPU Time:
-----------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                                 Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls
-----------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                                    inference_forward         6.95%      17.611ms        90.79%     230.160ms     115.080ms          84 B    -289.52 MB             2
                                         aten::linear         0.97%       2.470ms        73.37%     186.002ms       1.257ms     141.77 MB           0 B           148
                                          aten::addmm        67.58%     171.324ms        71.11%     180.263ms       1.218ms     141.77 MB     141.77 MB           148
                                  convert_to_features         4.90%      12.425ms         4.90%      12.425ms       6.212ms           0 B           0 B             2
                                           aten::gelu         4.81%      12.185ms         4.81%      12.185ms     507.712us      63.00 MB      63.00 MB            24
                                          aten::copy_         3.18%       8.062ms         3.18%       8.062ms      52.350us           0 B           0 B           154
                                      model_to_device         2.54%       6.432ms         2.82%       7.157ms       3.578ms           0 B           0 B             2
                   aten::scaled_dot_product_attention         0.13%     322.191us         2.76%       6.987ms     291.111us      15.75 MB    -252.00 KB            24
    aten::_scaled_dot_product_flash_attention_for_cpu         2.08%       5.284ms         2.63%       6.664ms     277.687us      16.00 MB      -3.05 MB            24
                                     aten::layer_norm         0.15%     368.760us         1.17%       2.961ms      59.228us      32.81 MB     -87.50 KB            50
                                  postprocess_results         1.12%       2.833ms         1.13%       2.857ms       1.428ms         -84 B         -84 B             2
                              aten::native_layer_norm         0.77%       1.955ms         1.02%       2.593ms      51.853us      32.90 MB           0 B            50
                                      aten::transpose         0.61%       1.545ms         0.87%       2.205ms       5.683us           0 B           0 B           388
                                           aten::view         0.77%       1.944ms         0.77%       1.944ms       3.739us           0 B           0 B           520
                                            aten::add         0.77%       1.940ms         0.77%       1.940ms      38.803us      32.81 MB      32.81 MB            50
                                              aten::t         0.23%     585.647us         0.56%       1.428ms       9.646us           0 B           0 B           148
                                        aten::reshape         0.20%     505.968us         0.43%       1.083ms       6.225us           0 B           0 B           174
                                     aten::as_strided         0.37%     938.021us         0.37%     938.021us       1.606us           0 B           0 B           584
                                         aten::expand         0.27%     680.095us         0.36%     918.211us       5.277us           0 B           0 B           174
                                          aten::empty         0.29%     739.725us         0.29%     739.725us       3.108us      36.31 MB      36.31 MB           238
-----------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 253.516ms

\n================================================================================\n

In [ ]:
result2

,sentence,logit,prediction,sentiment_score,textblob_prediction
0,Shares in the spin-off of South African e-commerce group Naspers surged more than 25% in the first minutes of their market debut in Amsterdam on Wednesday.,"[0.8374599, 0.09289622, 0.069643915]",positive,0.744564,0.250000
1,"Bob van Dijk, CEO of Naspers and Prosus Group poses at Amsterdam's stock exchange, as Prosus begins trading on the Euronext stock exchange in Amsterdam, Netherlands, September 11, 2019.","[0.3765054, 0.06876898, 0.5547256]",neutral,0.307736,0.000000
2,"REUTERS/Piroschka van de Wouw Prosus comprises Naspers' global empire of consumer internet assets, with the jewel in the crown a 31% stake in Chinese tech titan Tencent.","[0.1988723, 0.039865926, 0.76126176]",neutral,0.159006,0.000000
3,"There is 'way more demand than is even available, so that's good,' said the CEO of Euronext Amsterdam, Maurice van Tilburg.","[0.70401895, 0.07144888, 0.22453214]",positive,0.632570,0.533333
4,'It's going to be an interesting hour of trade after opening this morning.',"[0.5107952, 0.0971463, 0.39205858]",positive,0.413649,0.500000
5,"Euronext had given an indicative price of 58.70 euros per share for Prosus, implying a market value of 95.3 billion euros ($105 billion).","[0.31765544, 0.072268, 0.6100766]",neutral,0.245387,0.000000
6,The shares jumped to 76 euros on opening and were trading at 75 euros at 0719 GMT.,"[0.48225912, 0.066082776, 0.45165807]",positive,0.416176,0.000000

In [ ]:
print(f'Average sentiment is %.2f.' % (result2.sentiment_score.mean()))

Average sentiment is 0.42.

## Summary

This notebook provides baseline profiling data for:
1. **Training operations**: Data loading, forward pass, loss calculation, backward pass, optimizer step
2. **Inference operations**: Tokenization, feature conversion, model forward pass, postprocessing

The profiling output shows CPU time (and CUDA time if available) for each operation, which can be used to identify optimization opportunities.